#
#
obj-$(CONFIG_MACH_TTC_DKB) += lcd_tpo.o lcd_truly.o lcd_sharp.o
obj-$(CONFIG_UIO_HDMI) += lcd_hdmi.o
obj-$(CONFIG_MACH_YELLOWSTONE) += lcd_mipi.o
obj-$(CONFIG_MACH_ARUBA_TD) += lcd_mipi.o
obj-$(CONFIG_MACH_EMEIDKB) += lcd_mipi.o
obj-$(CONFIG_MACH_HENDRIX) += lcd_hendrix.o
obj-$(CONFIG_MACH_LT02) += lcd_tc35876x_boeot_wsvga_mipi.o
obj-$(CONFIG_MACH_COCOA7) += lcd_tc35876x_boeot_wsvga_mipi.o
