#
#  Makefile for the kernel Sensor device drivers.
#

#  Object files in subdirectories
obj-$(CONFIG_SENSORS_BMC150)	+= bma2x2_driver.o bst_sensor_common.o bmm050_driver.o bmm050.o
obj-$(CONFIG_SENSORS_GP2A0X0)	+= gp2a0x0.o
obj-$(CONFIG_SENSORS_ASP01)	+= asp01.o
obj-$(CONFIG_SENSORS_CORE)	+= core/
