# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o
obj-$(CONFIG_SWITCH_88PM860X_HS)    += 88pm860x_headset.o
obj-$(CONFIG_SWITCH_88PM800_HS)	+= 88pm800_headset.o
obj-$(CONFIG_SWITCH_88PM800_HS_SEC)	 += 88pm800_headset_sec.o

#KSND Samsung Jack
obj-$(CONFIG_SAMSUNG_JACK) += sec_jack.o
