#
# This Makefile is just to invoke the Makefile in the build directory.
#
# MODEM_ROOT = $(shell pwd)
MODEM_ROOT = $(srctree)/drivers/marvell/marvell-telephony/drivers/cimodemtty
include $(MODEM_ROOT)/build/Makefile
