obj-$(CONFIG_MARVELL_IN_KERNEL_GC1000)		+= graphics/galcore_src/
obj-$(CONFIG_MARVELL_IN_KERNEL_SD8787)		+= sd8787/
obj-$(CONFIG_MARVELL_IN_KERNEL_TELEPHONY)	+= marvell-telephony/drivers/
obj-$(CONFIG_MARVELL_IN_KERNEL_GEU)		+= security/wtpsp/drv/src/
obj-$(CONFIG_MARVELL_IN_KERNEL_PHYSRW)		+= physrw/
