EXTRA_CFLAGS += -DBMM_USE_BASIC_I2C_FUNC

obj-$(CONFIG_SENSORS_GP2A002S)	+= gp2a.o
obj-$(CONFIG_SENSORS_BMA2X2)	+= bma2x2_driver.o bst_sensor_common.o      
obj-$(CONFIG_SENSORS_BMM050)	+= bmm050_driver.o bmm050.o

